spring:
  application:
    name: rip-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jackson:
    time-zone: Europe/Moscow
  main:
    banner-mode: off
server:
  port: 8080

minio:
  endpoint: ${MINIO_URL}
  key:
    secret: minio124
    access: minio
  bucket.name: categories
logging:
  level:
    root: info
    com:
      bmstu:
        lab: trace

jwt:
  secret: vcNreNuHt307dFou/OD1Uc3w97+sLcJpi0nBsWbNK5czapXowy++EDOBbJ6AVBj1e+CxDL4d2M8YZlV5KNu2UA==
  expiration-ms: 86400000
  cookie.key: "jwt_token"
  blacklist.ttl-hours: 2

async:
  service:
    url: http://localhost:8001/
    token: lab8token
