spring:
  application:
    name: rip-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/labdb
    username: labuser
    password: labpass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jackson:
    time-zone: Europe/Moscow
  main:
    banner-mode: off
server:
  port: 8080

minio:

  endpoint: http://localhost:9000
  key:
    secret: minio124
    access: minio
  bucket.name: images
logging:
  level:
    root: error
