spring:
  application:
    name: rip-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/labdb
    username: labuser
    password: labpass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
server:
  port: 8080

minio:
  base-url: http://127.0.0.1:9000/images/
  endpoint: http://localhost:9000
  key:
    secret: minio
    access: minio124
